### PR TITLE
Add Cordelia Style

### PR DESCRIPTION
**Pull request by VivienLN**
Note: Changes on shylock's menu is my text editor removing trailing spaces and tabs

### CODE REVIEW

**Comment by botelho** [comment]
Hi Vivien, thanks a lot for the contribution. The effect looks really nice but I think it would be possible to achieve the same results without animating the width/right/left which are expensive to animate. Instead you could use transforms like translate3d and scale3d, sort of what we are doing in the Sebastian effect. Also note that prefix properties come before the unprefixed ones. It would be great if you could edit it; or if you are not sure we can also merge this and fix it. Let me know and thanks. Cheers.

**Comment by VivienLN** [comment]
Hi, thanks for the feedback :)
I am at work right now so I may not be able to edit it quickly, but if you want to fix it yourself you are more than welcome!
As for prefixes, you're right indeed (I usually use autoprefixer and didn't pay attention)

Thank you

**Comment by crnacura** [comment]
Hi Vivien, ok cool, we've edited it and it's live now :) Thanks and cheers

**Comment by VivienLN** [comment]
Nice, thank you! :)

**Comment by crnacura** [comment]
:)

**Pull request merged**
